import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type ArticleExampleContentTypeModel = IContentItem<{
  body: Elements.RichTextElement;
  title: Elements.TextElement;
  url: Elements.UrlSlugElement;
}>;
