import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type ComponentCtaModel = IContentItem<{
  buttonLink: Elements.TextElement;
  buttonText: Elements.TextElement;
  headline: Elements.TextElement;
  subheadline: Elements.TextElement;
}>;
