import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type LandingPageModel = IContentItem<{
  content: Elements.RichTextElement;
  urlSlug: Elements.UrlSlugElement;
  title: Elements.TextElement;
}>;
